export default class CommonConstants {
  /**
   * Small font size.
   */
  static readonly SET_SIZE_SMALL: number = 14;

  /**
   * Normal font size.
   */
  static readonly SET_SIZE_NORMAL: number = 16;

  /**
   * Large font size.
   */
  static readonly SET_SIZE_LARGE: number = 18;

  /**
   * Extra large font size.
   */
  static readonly SET_SIZE_EXTRA_LARGE: number = 20;

  /**
   * Huge font size.
   */
  static readonly SET_SIZE_HUGE: number = 24;

  static readonly SET_FONT_WEIGHT_NORMAL: number = 400;

  static readonly SET_FONT_WEIGHT_LARGE: number = 500;

  static readonly SET_BUTTON_HEIGHT_NORMAL: string = '100%';

  static readonly SET_PAGE_WIDTH: string = '100%';

  static readonly SET_PAGE_HEIGHT: string = '100%';
}